name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Nuevas Características"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Correcciones de Errores"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Mantenimiento"
    labels:
      - "chore"
  - title: "🛠️ Mejoras en la Funcionalidad"
    labels:
      - "improvement"
  - title: "📚 Documentación"
    labels:
      - "documentation"
  - title: "🧪 Pruebas Adicionales"
    labels:
      - "testing"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Cambios

  $CHANGES
