services:
  discord-bot:
    build:
      context: .
      dockerfile: ./dockerfile.local
    container_name: bot
    environment:
      - DISCORDTOKEN=${DISCORDTOKEN}
      - COMMANDPREFIX=${COMMANDPREFIX}
    ports:
      - "8080:8080"
    networks:
      - monitoring-net
    restart: always
  
  pyroscope:
    image: grafana/pyroscope:1.6.0
    container_name: pyroscope
    ports:
      - "4040:4040"
    environment:
      - PYROSCOPE_SCRAPE_ENDPOINT_ENABLED=true
    networks:
      - monitoring-net
    restart: always

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net
    restart: always


  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config:/etc/grafana-config
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-net
    restart: always


  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
