services:
  discord-bot:
    image: ${AWS_ECR_REPOSITORY}:${GITHUB_SHA}
    container_name: bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - REGION=${REGION}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    networks:
      - monitoring-net
    restart: always

  prometheus:
    image: prom/prometheus:v2.51.2
    #platform: linux/arm64/v8
    platform: linux/amd64
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net
    restart: always

  loki:
    image: grafana/loki:2.9.0
    # para arm64 platform: linux/arm64/v8
    platform: linux/amd64
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki:/etc/loki
    networks:
      - monitoring-net
    restart: always

  promtail:
    image: grafana/promtail:2.9.0
    # para arm64 platform: linux/arm64/v8
    platform: linux/amd64
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./logs:/logs
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring-net

  pyroscope:
    image: grafana/pyroscope:1.6.0
    #platform: linux/arm64
    platform: linux/amd64
    container_name: pyroscope
    ports:
      - "4040:4040"
    environment:
      - PYROSCOPE_SCRAPE_ENDPOINT_ENABLED=true
    networks:
      - monitoring-net
    restart: always

  grafana:
    image: grafana/grafana:11.0.0
    # para arm64 platform: linux/arm64
    platform: linux/amd64
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config:/etc/grafana-config
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-net
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.8.1
    # para arm64 platform: linux/arm64/v8
    platform: linux/amd64
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
