server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: discord_bot_logs
    static_configs:
      - targets:
          - bot:8080 
        labels:
          job: discord_bot
          __path__: /logs/*.log 
