apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-cluster
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  publishNotReadyAddresses: true