name: Go Continuous Delivery Pipeline

on:
  workflow_run:
    workflows: ["Go Development Pipeline"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    name: Deploy a EC2
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Logearse a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Buildear y pushear la imagen
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/butakero-bot-aws:latest

      - name: Deploy a EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            sudo docker stop butakero-bot || true
            sudo docker rm butakero-bot || true
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/butakero-bot-aws:latest
            sudo docker run -d --name butakero-bot -e DISCORDTOKEN=${{ secrets.DISCORDTOKEN  }} -e COMMANDPREFIX=${{ secrets.COMMANDPREFIX }} -p 80:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/butakero-bot-aws:latest
