name: Go Continuous Delivery Pipeline

on:
  workflow_run:
    workflows: ["Go Development Pipeline"]
    types:
      - completed
    branches:
      - master

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPOSITORY }}

      - name: Build and Push Docker Image to ECR
        run: |
          docker build -t ${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }} -f dockerfile.aws .
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }}

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /opt/app/ButakeroMusicBotGo
            docker-compose -f production-docker-compose.yml pull
            docker-compose -f production-docker-compose.yml up -d --no-deps --build discord-bot

