name: Increment Version and Create Release

on:
  workflow_run:
    workflows: ["Go Continuous Delivery Pipeline"]
    types:
      - completed

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read current version
        id: read_version
        run: echo "::set-output name=version::$(cat version.yaml | yq r - version)"

      - name: Increment version
        id: increment_version
        run: echo "::set-output name=version::$(echo ${{ steps.read_version.outputs.version }} | awk -F. '{$NF+=1; OFS="."; print}' )"

      - name: Save incremented version
        run: |
          echo "version: ${{ steps.increment_version.outputs.version }}" > version.yaml

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ steps.increment_version.outputs.version }}
          release_name: Release v${{ steps.increment_version.outputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
